# Site settings
title: The Vape Shoppe
email: thevapeshoppes@gmail.com
url: www.vapeshoppelhc.com
description: "Custom Made E-Juice, Vape Hardware, and Much more."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  secondary: '#808080'

# Footer settings
footer: The Vape Shoppe

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/thevapeshoppehavasu/

# Build settings
markdown: kramdown
permalink: pretty
